name: Update README

on:
  schedule:
    - cron: "0 0 * * *" # 매일 자정(UTC 기준)에 실행
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch today's commit count
        run: |
          TODAY_COMMITS=$(curl -s "https://api.github.com/users/Jaewoong-Hwang/events" | jq '[.[] | select(.type=="PushEvent") | .created_at | select(startswith("'$(date -u +%Y-%m-%d)'"))] | length')
          echo "TODAY_COMMITS=$TODAY_COMMITS" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "/## 📊 Today’s Commits/c\## 📊 Today’s Commits: $TODAY_COMMITS" README.md

      - name: Commit and Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}  # Secret 이름 확인 필요
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "자동 업데이트: 오늘의 커밋 수 추가" || exit 0
          git push https://x-access-token:${GH_PAT}@github.com/Jaewoong-Hwang/Jaewoong-Hwang.git
